version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: twitch-stalker-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./apps/server/.env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: twitch-stalker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
